import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";
//import { Geist, Geist_Mono } from "next/font/google";
import { ReactQueryProvider } from "@/react-query-provider";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";

/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <TooltipProvider>
          <ReactQueryProvider>
            <NuqsAdapter>
              {children}
              <Toaster />
            </NuqsAdapter>
          </ReactQueryProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
